service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  findAllRecipe:
    handler: handler.findAllRecipes
    events:
      - http:
          method: get
          path: recipes
  findOneRecipe:
      handler: handler.findOneRecipes
      events:
        - http:
            method: get
            path: recipes/{uid}
