service:
  name: xebicon17-supercook

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs6.10

functions:
  findAllRecipe:
    handler: handler.findAllRecipes
    events:
      - http:
          method: get
          path: recipes
  findOneRecipe:
    handler: handler.findOneRecipes
    events:
      - http:
          method: get
          path: recipes/{uid}
